### ISSUE TITLE
day 1 exercise level 3 both questions pending

### ISSUE THREAD

**Issue by iamtalhaasghar** [iamreyan/python-in-30-days#1]
These 2 questions are pending, 
https://github.com/Asabeneh/30-Days-Of-Python#exercise-level-3

**Comment by iamreyanasghar** [comment]
Question one done
how to solve second one

**Comment by iamtalhaasghar** [comment]
> Question one done how to solve second one

I don't see any changes in day 1 files. Commit is empty https://github.com/iamreyan/python-in-30-days/commit/235ec090a4c16d009c866a50c26c3931de5bb7bd

>  how to solve second one

Steps you can take:

1. Search on youtube how to calculate euclidean distance. Learn the concepts first and then try again. 
2. Also check this [tutorial](https://www.geeksforgeeks.org/program-calculate-distance-two-points/).
